
console.log("Hello World")
const a=47; 
var b=17;
let c=2;
let soma=a+b+c
let subtracao= a-b-c;
let multiplicacao=a*b*c;
let divisao=(a-b)/c
let modulo=(a*b)%c


console.log("Resultado da Soma é " + soma)
console.log("Resultado da Subtração é " + subtracao)
console.log("Resultado da Multiplicação é " + multiplicacao)
console.log("Resultado da Divisão é " + divisao)
console.log("Resultado da Módulo é " + modulo)